version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
  
  server:
    build: ./server
    ports:
      - '3000:3000'

    links: 
      - mongodb

  client:
    build: ./client
    ports:
      - 80:80
 
